### ISSUE TITLE
Remove ability to open the same file multiple times

### ISSUE THREAD

**Issue by EJBQ** [prmr/JetUML#29]
This is in both the current version and JetUML. It's possible to open  a file, then open it again and get separate windows. This seems unintentional.

**Comment by EJBQ** [comment]
When fixing, make sure to check for edited versions of the same file as well.

**Comment by prmr** [comment]
@EJBQ I'm not sure I understand your comment. I've fixed the issue in branch Issue0029. Does this address your concern?

**Comment by EJBQ** [comment]
@prmr I'm still seeing the issue when I pull branch 29 right now. If I open a file multiple times, it opens in multiple windows, when I imagine correct functionality would be to pop up an error message that it's open already.

**Comment by EJBQ** [comment]
My comment was that edited files have an asterisk attached to them in the window header. I wasn't sure if this was included in how JetUML counts the file name, but the same file should  not open again even if the version in the window has been edited. (so watch for this asterisk when checking the file name against the current open ones)

**Comment by prmr** [comment]
This is weird because it works for me. Are you sure you rebuilt since switching branches? The thing about the asterisk is a non-issue. I rebuilt the entire file handling to work with absolute files for comparisons, etc.
